title:          Terry Migwi
logo:           /docs/assets/Portfolio_pic.png
description:    Data Scientist
show_downloads:  false
theme:           jekyll-theme-minimal

social:

  linkedin: https://www.linkedin.com/in/terry-migwi-a81082137/
  github: /https://github.com/Terry-Migwi

