title:          Terry Migwi
logo:           /docs/assets/Portfolio_pic.png
description:    Data Scientist
show_downloads:  false
theme:           jekyll-theme-minimal
index:           README.md

#social:

  #linkedin:   terry-migwi-a81082137
  #github:     Terry-Migwi 

  # _config.yml

linkedin_url: https://www.linkedin.com/in/terry-migwi-a81082137
github_url: https://github.com/Terry-Migwi 


