title:          Terry Migwi
logo:           /docs/assets/passport_photo.jpg
description: >-  
       Data Scientist
show_downloads:  false
theme:           jekyll-theme-minimal
index:           README.md

social: 
  linkedin_url: https://www.linkedin.com/in/terry-migwi-a81082137
  github_url:   https://github.com/Terry-Migwi 

#social:

 # linkedin:   [LinkedIn]({{ site.linkedin_url }})
 # github:     [GitHub]({{ site.github_url }})

  # _config.yml




