title:          Terry Migwi
logo:           /docs/assets/Portfolio_pic.png
description:    Data Scientist
show_downloads:  false
theme:           jekyll-theme-minimal

social:

  linkedin:   terry-migwi-a81082137
  github:     Terry-Migwi

